In [337]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [338]:
# load data
df = pd.read_csv('data.csv', header=None)
data = df.values

In [339]:
# load labels
df = pd.read_csv('ref.csv', header=None)
classes = ['N', 'A', 'O', '~']
labels = np.array([ classes.index(df[1][i]) for i in range(df.shape[0]) ])

In [340]:
# split data
normal = data[np.nonzero(labels == 0)]
afib = data[np.nonzero(labels == 1)]
other = data[np.nonzero(labels == 2)]
noisy = data[np.nonzero(labels == 3)]

In [341]:
# play with data
for i in range(data.shape[1]):
    print(data[:, i].max())
    print(data[:, i].min())
    print(data[:, i].mean())
    print(data[:, i].std())
    print(np.histogram(data[:, i]))
    print('-------------------')

47.543
-2.4958
2.3431988742990613e-07
0.9999392293427487
(array([8519,    3,    2,    1,    1,    0,    0,    1,    0,    1]), array([-2.4958 ,  2.50808,  7.51196, 12.51584, 17.51972, 22.5236 ,
       27.52748, 32.53136, 37.53524, 42.53912, 47.543  ]))
-------------------
3.9186
-4.9543
-2.2586069418242227e-07
0.9999412489440329
(array([  18,    7,  125,  492, 1783, 3077, 2178,  751,   94,    3]), array([-4.9543 , -4.06701, -3.17972, -2.29243, -1.40514, -0.51785,
        0.36944,  1.25673,  2.14402,  3.03131,  3.9186 ]))
-------------------
3.4231
-4.723
1.6146810513624818e-09
0.9999407389147955
(array([  16,    9,  131,  464, 1406, 2730, 2402, 1103,  258,    9]), array([-4.723  , -3.90839, -3.09378, -2.27917, -1.46456, -0.64995,
        0.16466,  0.97927,  1.79388,  2.60849,  3.4231 ]))
-------------------
9.395
-0.97464
-1.4265126641596278e-07
0.9999410606901421
(array([5724, 1643,  760,  284,   86,   26,    2,    1,    1,    1]), array([-0.97464 ,  0.062324,  1.099288,  2.136252,  3

(array([8520,    3,    1,    2,    0,    0,    1,    0,    0,    1]), array([-0.12873 ,  6.464843, 13.058416, 19.651989, 26.245562, 32.839135,
       39.432708, 46.026281, 52.619854, 59.213427, 65.807   ]))
-------------------
67.365
-0.036849
5.7777908067274957e-08
0.9999434002359462
(array([8520,    3,    1,    2,    0,    0,    1,    0,    0,    1]), array([-3.68490000e-02,  6.70333590e+00,  1.34435208e+01,  2.01837057e+01,
        2.69238906e+01,  3.36640755e+01,  4.04042604e+01,  4.71444453e+01,
        5.38846302e+01,  6.06248151e+01,  6.73650000e+01]))
-------------------
67.381
-0.030188
3.94805347051478e-08
0.9999421268874794
(array([8520,    3,    1,    2,    0,    0,    1,    0,    0,    1]), array([-3.01880000e-02,  6.71093080e+00,  1.34520496e+01,  2.01931684e+01,
        2.69342872e+01,  3.36754060e+01,  4.04165248e+01,  4.71576436e+01,
        5.38987624e+01,  6.06398812e+01,  6.73810000e+01]))
-------------------
64.881
-0.15857000000000002
6.801125699203802e-09
0.99993

(array([8520,    3,    1,    2,    0,    0,    1,    0,    0,    1]), array([-0.18041 ,  6.585631, 13.351672, 20.117713, 26.883754, 33.649795,
       40.415836, 47.181877, 53.947918, 60.713959, 67.48    ]))
-------------------
67.492
-0.18002
-1.489212007535797e-08
0.9999420481475902
(array([8520,    3,    1,    2,    0,    0,    1,    0,    0,    1]), array([-0.18002 ,  6.587182, 13.354384, 20.121586, 26.888788, 33.65599 ,
       40.423192, 47.190394, 53.957596, 60.724798, 67.492   ]))
-------------------
67.48100000000001
-0.17703
7.223264540639155e-08
0.9999432023081009
(array([8520,    3,    1,    2,    0,    0,    1,    0,    0,    1]), array([-0.17703 ,  6.588773, 13.354576, 20.120379, 26.886182, 33.651985,
       40.417788, 47.183591, 53.949394, 60.715197, 67.481   ]))
-------------------
67.495
-0.18259
5.3705440902029074e-08
0.9999389072233625
(array([8520,    3,    1,    2,    0,    0,    1,    0,    0,    1]), array([-0.18259 ,  6.585169, 13.352928, 20.120687, 26.888446, 33.

(array([8520,    4,    0,    1,    0,    1,    1,    0,    0,    1]), array([-4.41010000e-02,  6.59930910e+00,  1.32427192e+01,  1.98861293e+01,
        2.65295394e+01,  3.31729495e+01,  3.98163596e+01,  4.64597697e+01,
        5.31031798e+01,  5.97465899e+01,  6.63900000e+01]))
-------------------
66.389
-0.026324
2.0450281424917018e-08
0.9999414154535319
(array([8520,    4,    0,    1,    0,    1,    1,    0,    0,    1]), array([-2.63240000e-02,  6.61520840e+00,  1.32567408e+01,  1.98982732e+01,
        2.65398056e+01,  3.31813380e+01,  3.98228704e+01,  4.64644028e+01,
        5.31059352e+01,  5.97474676e+01,  6.63890000e+01]))
-------------------
66.389
-0.02636
2.0755159469345053e-08
0.9999412274702137
(array([8520,    4,    0,    1,    0,    1,    1,    0,    0,    1]), array([-2.6360000e-02,  6.6151760e+00,  1.3256712e+01,  1.9898248e+01,
        2.6539784e+01,  3.3181320e+01,  3.9822856e+01,  4.6464392e+01,
        5.3105928e+01,  5.9747464e+01,  6.6389000e+01]))
--------------

1.0938086304369058e-07
0.999946515921371
(array([8520,    4,    0,    1,    0,    1,    1,    0,    0,    1]), array([-2.59130000e-02,  6.61557830e+00,  1.32570696e+01,  1.98985609e+01,
        2.65400522e+01,  3.31815435e+01,  3.98230348e+01,  4.64645261e+01,
        5.31060174e+01,  5.97475087e+01,  6.63890000e+01]))
-------------------
66.389
-0.025698000000000002
-1.981707317110628e-08
0.9999417612999552
(array([8520,    4,    0,    1,    0,    1,    1,    0,    0,    1]), array([-2.56980000e-02,  6.61577180e+00,  1.32572416e+01,  1.98987114e+01,
        2.65401812e+01,  3.31816510e+01,  3.98231208e+01,  4.64645906e+01,
        5.31060604e+01,  5.97475302e+01,  6.63890000e+01]))
-------------------
66.311
-0.034024
-1.5623827393191635e-08
0.9999401125895004
(array([8520,    4,    0,    1,    0,    1,    1,    0,    0,    1]), array([-3.40240000e-02,  6.60047840e+00,  1.32349808e+01,  1.98694832e+01,
        2.65039856e+01,  3.31384880e+01,  3.97729904e+01,  4.64074928e+01,
        

-0.026844
-1.817542213710721e-08
0.9999406733563004
(array([8520,    4,    0,    1,    0,    1,    1,    0,    0,    1]), array([-2.68440000e-02,  6.61474040e+00,  1.32563248e+01,  1.98979092e+01,
        2.65394936e+01,  3.31810780e+01,  3.98226624e+01,  4.64642468e+01,
        5.31058312e+01,  5.97474156e+01,  6.63890000e+01]))
-------------------
66.389
-0.025976999999999997
1.2206848029735774e-07
0.9999467418137807
(array([8520,    4,    0,    1,    0,    1,    1,    0,    0,    1]), array([-2.59770000e-02,  6.61552070e+00,  1.32570184e+01,  1.98985161e+01,
        2.65400138e+01,  3.31815115e+01,  3.98230092e+01,  4.64645069e+01,
        5.31060046e+01,  5.97475023e+01,  6.63890000e+01]))
-------------------
66.389
-0.025861000000000002
-3.5178236379753065e-09
0.9999420122527364
(array([8520,    4,    0,    1,    0,    1,    1,    0,    0,    1]), array([-2.58610000e-02,  6.61562510e+00,  1.32571112e+01,  1.98985973e+01,
        2.65400834e+01,  3.31815695e+01,  3.98230556e+01,  4

(array([   7,   25,  242, 8183,   56,    8,    4,    1,    0,    2]), array([-13.461,  -9.384,  -5.307,  -1.23 ,   2.847,   6.924,  11.001,
        15.078,  19.155,  23.232,  27.309]))
-------------------
37.411
-55.836000000000006
1.2983114448183446e-08
0.9999362630286789
(array([   1,    1,    0,    0,    0, 7567,  956,    1,    1,    1]), array([-55.836 , -46.5113, -37.1866, -27.8619, -18.5372,  -9.2125,
         0.1122,   9.4369,  18.7616,  28.0863,  37.411 ]))
-------------------
11.173
-14.017999999999999
1.0343105065388955e-07
0.9999402092991353
(array([   2,    8,   20,   63,  277, 7997,  114,   33,    8,    6]), array([-14.018 , -11.4989,  -8.9798,  -6.4607,  -3.9416,  -1.4225,
         1.0966,   3.6157,   6.1348,   8.6539,  11.173 ]))
-------------------
21.246
-34.49
3.350023452165209e-07
0.9999401991214176
(array([   1,    0,    0,    3,   15,  469, 8015,   23,    1,    1]), array([-34.49  , -28.9164, -23.3428, -17.7692, -12.1956,  -6.622 ,
        -1.0484,   4.5252,  10.09

-12.89
1.7433513133373493e-07
0.9999431395144576
(array([   2,    5,   36, 7245, 1149,   79,    8,    2,    1,    1]), array([-12.89  ,  -9.5478,  -6.2056,  -2.8634,   0.4788,   3.821 ,
         7.1632,  10.5054,  13.8476,  17.1898,  20.532 ]))
-------------------
33.455
-19.075
2.554737335860009e-07
0.9999425496650678
(array([   1,    0,   25, 8244,  247,    9,    0,    0,    1,    1]), array([-19.075, -13.822,  -8.569,  -3.316,   1.937,   7.19 ,  12.443,
        17.696,  22.949,  28.202,  33.455]))
-------------------
36.466
-9.4045
4.898569418183338e-08
0.9999415453477816
(array([   5, 4226, 4246,   43,    6,    0,    0,    1,    0,    1]), array([-9.4045 , -4.81745, -0.2304 ,  4.35665,  8.9437 , 13.53075,
       18.1178 , 22.70485, 27.2919 , 31.87895, 36.466  ]))
-------------------
22.35
-11.376
-3.1636960551827458e-09
0.9999386137091392
(array([   2,    6,  122, 8052,  328,   15,    1,    0,    0,    2]), array([-11.376 ,  -8.0034,  -4.6308,  -1.2582,   2.1144,   5.487 ,
        

(array([   1,    0,    2,    0,    0,    0,    1,    0, 8520,    4]), array([-64.212  , -56.80715, -49.4023 , -41.99745, -34.5926 , -27.18775,
       -19.7829 , -12.37805,  -4.9732 ,   2.43165,   9.8365 ]))
-------------------
42.771
-20.413
-2.0034005629761116e-08
0.9999401016799965
(array([   2,    9,   68, 8426,   11,    6,    4,    1,    0,    1]), array([-20.413 , -14.0946,  -7.7762,  -1.4578,   4.8606,  11.179 ,
        17.4974,  23.8158,  30.1342,  36.4526,  42.771 ]))
-------------------
58.825
-24.726
-4.3461538460689634e-08
0.9999439115835302
(array([   1,    7, 8267,  248,    0,    3,    1,    0,    0,    1]), array([-24.726 , -16.3709,  -8.0158,   0.3393,   8.6944,  17.0495,
        25.4046,  33.7597,  42.1148,  50.4699,  58.825 ]))
-------------------
21.066
-50.996
-2.1145286116071718e-07
0.9999445838500454
(array([   1,    0,    1,    1,    4,    6,   70, 8437,    6,    2]), array([-50.996 , -43.7898, -36.5836, -29.3774, -22.1712, -14.965 ,
        -7.7588,  -0.5526,   6

0.9999416253786083
(array([   2,    1,   13,  308, 8171,   23,    6,    0,    1,    3]), array([-20.901 , -15.8952, -10.8894,  -5.8836,  -0.8778,   4.128 ,
         9.1338,  14.1396,  19.1454,  24.1512,  29.157 ]))
-------------------
29.205
-12.828
-1.0712124765208239e-07
0.9999399517949231
(array([   9,   21, 1047, 7399,   41,    6,    2,    1,    1,    1]), array([-12.828 ,  -8.6247,  -4.4214,  -0.2181,   3.9852,   8.1885,
        12.3918,  16.5951,  20.7984,  25.0017,  29.205 ]))
-------------------
20.684
-14.946
1.656977016908355e-07
0.999943232835089
(array([   3,   10,   27,  467, 7938,   64,   10,    3,    4,    2]), array([-14.946, -11.383,  -7.82 ,  -4.257,  -0.694,   2.869,   6.432,
         9.995,  13.558,  17.121,  20.684]))
-------------------
27.88
-16.944000000000003
-1.1504924953350098e-07
0.9999369871854416
(array([   4,    3,   55, 8228,  214,   18,    2,    1,    2,    1]), array([-16.944 , -12.4616,  -7.9792,  -3.4968,   0.9856,   5.468 ,
         9.9504,  14.4328

(array([   4,   10, 8408,   45,    3,   35,    8,    8,    6,    1]), array([-9.3578 , -6.15672, -2.95564,  0.24544,  3.44652,  6.6476 ,
        9.84868, 13.04976, 16.25084, 19.45192, 22.653  ]))
-------------------
22.64
-9.3589
-8.360694183481744e-08
0.9999410341680045
(array([   4,   10, 8407,   46,    3,   35,    8,    8,    6,    1]), array([-9.3589 , -6.15901, -2.95912,  0.24077,  3.44066,  6.64055,
        9.84044, 13.04033, 16.24022, 19.44011, 22.64   ]))
-------------------
22.64
-9.3589
-9.532129454625073e-08
0.9999416110550544
(array([   4,   10, 8407,   46,    3,   35,    8,    8,    6,    1]), array([-9.3589 , -6.15901, -2.95912,  0.24077,  3.44066,  6.64055,
        9.84044, 13.04033, 16.24022, 19.44011, 22.64   ]))
-------------------
22.64
-9.359
8.863742965828093e-08
0.9999428862567535
(array([   4,   10, 8407,   46,    3,   35,    8,    8,    6,    1]), array([-9.359 , -6.1591, -2.9592,  0.2407,  3.4406,  6.6405,  9.8404,
       13.0403, 16.2402, 19.4401, 22.64  ]))
-

0.9999409973658889
(array([   4,   11,   61, 8377,   56,   11,    5,    2,    0,    1]), array([-17.142 , -12.1567,  -7.1714,  -2.1861,   2.7992,   7.7845,
        12.7698,  17.7551,  22.7404,  27.7257,  32.711 ]))
-------------------
22.666
-10.89
2.9377345216876053e-08
0.9999424073593494
(array([   3,   11,  120, 8347,   17,    7,    7,    6,    3,    7]), array([-10.89  ,  -7.5344,  -4.1788,  -0.8232,   2.5324,   5.888 ,
         9.2436,  12.5992,  15.9548,  19.3104,  22.666 ]))
-------------------
40.411
-18.916
5.29112335818778e-07
0.9999424475341606
(array([   5,    8,  132, 8345,   32,    5,    0,    0,    0,    1]), array([-18.916 , -12.9833,  -7.0506,  -1.1179,   4.8148,  10.7475,
        16.6802,  22.6129,  28.5456,  34.4783,  40.411 ]))
-------------------
22.17
-20.167
1.145872420307852e-08
0.9999409582271428
(array([   2,    2,    5,   36, 8247,  206,   17,    5,    4,    4]), array([-20.167 , -15.9333, -11.6996,  -7.4659,  -3.2322,   1.0015,
         5.2352,   9.4689,  13

0.9999407002668419
(array([  63, 4446, 3389,  485,   92,   28,   12,    6,    6,    1]), array([-2.9909 , -1.55231, -0.11372,  1.32487,  2.76346,  4.20205,
        5.64064,  7.07923,  8.51782,  9.95641, 11.395  ]))
-------------------
12.710999999999999
-2.9834
-2.058747654238924e-08
0.9999416057623912
(array([  71, 5614, 2371,  395,   49,   13,    5,    6,    3,    1]), array([-2.9834 , -1.41396,  0.15548,  1.72492,  3.29436,  4.8638 ,
        6.43324,  8.00268,  9.57212, 11.14156, 12.711  ]))
-------------------
8.3165
-3.4006
-1.7344512195338592e-07
0.9999409870514658
(array([  50,  720, 4519, 2444,  611,  129,   32,   16,    5,    2]), array([-3.4006 , -2.22889, -1.05718,  0.11453,  1.28624,  2.45795,
        3.62966,  4.80137,  5.97308,  7.14479,  8.3165 ]))
-------------------
7.0472
-3.5172
7.700867729864925e-08
0.9999421415592736
(array([  44,  115, 3599, 2908, 1332,  454,   75,    0,    0,    1]), array([-3.5172 , -2.46076, -1.40432, -0.34788,  0.70856,  1.765  ,
        2.821

(array([6493, 1306,  580,  117,   22,    8,    1,    0,    0,    1]), array([-0.78239 ,  0.444749,  1.671888,  2.899027,  4.126166,  5.353305,
        6.580444,  7.807583,  9.034722, 10.261861, 11.489   ]))
-------------------
11.238
-0.7891
1.657012194831052e-08
0.9999417338093098
(array([6413, 1304,  648,  132,   24,    6,    0,    0,    0,    1]), array([-0.7891 ,  0.41361,  1.61632,  2.81903,  4.02174,  5.22445,
        6.42716,  7.62987,  8.83258, 10.03529, 11.238  ]))
-------------------
0.16832
-13.495999999999999
-3.585342401514404e-06
0.9999296635616194
(array([  26,    0,    4,    4,   15,    9,   29,   68,  169, 8204]), array([-13.496   , -12.129568, -10.763136,  -9.396704,  -8.030272,
        -6.66384 ,  -5.297408,  -3.930976,  -2.564544,  -1.198112,
         0.16832 ]))
-------------------
0.082852
-16.577
-1.54784240150233e-06
0.9999636467252966
(array([  24,    0,    1,    1,    1,   18,    0,    8,   24, 8451]), array([-16.577    , -14.9110148, -13.2450296, -11.5790444,

0.32861
-9.2223
3.9410647279011804e-07
0.9999382841110087
(array([  61,    3,    2,    7,   47,   20,   46,   79,  222, 8041]), array([-9.2223  , -8.267209, -7.312118, -6.357027, -5.401936, -4.446845,
       -3.491754, -2.536663, -1.581572, -0.626481,  0.32861 ]))
-------------------
0.61639
-11.094000000000001
-1.488836772983174e-07
0.9999418985732024
(array([   1,    1,    6,   17,   33,   61,  129,  207,  791, 7282]), array([-11.094   ,  -9.922961,  -8.751922,  -7.580883,  -6.409844,
        -5.238805,  -4.067766,  -2.896727,  -1.725688,  -0.554649,
         0.61639 ]))
-------------------
0.27541
-11.72
1.7702802532808283e-06
0.9999203201926944
(array([  41,    0,    0,    3,   59,    0,    0,    8,   96, 8321]), array([-11.72    , -10.520459,  -9.320918,  -8.121377,  -6.921836,
        -5.722295,  -4.522754,  -3.323213,  -2.123672,  -0.924131,
         0.27541 ]))
-------------------
0.42378999999999994
-16.037
-4.342800187613166e-07
0.9999474146943942
(array([  15,    0,    0,   

(array([1157, 1940, 2039, 1476,  963,  535,  265,  101,   38,   14]), array([-1.6644 , -1.07159, -0.47878,  0.11403,  0.70684,  1.29965,
        1.89246,  2.48527,  3.07808,  3.67089,  4.2637 ]))
-------------------
4.7345
-1.9783
1.9609990619124526e-07
0.9999413109966482
(array([ 578, 1876, 2363, 1899,  994,  496,  202,   85,   26,    9]), array([-1.9783 , -1.30702, -0.63574,  0.03554,  0.70682,  1.3781 ,
        2.04938,  2.72066,  3.39194,  4.06322,  4.7345 ]))
-------------------
14.193
-0.9459
1.4635553471039972e-07
0.9999428353685361
(array([6829, 1315,  301,   63,   12,    4,    1,    0,    1,    2]), array([-0.9459 ,  0.56799,  2.08188,  3.59577,  5.10966,  6.62355,
        8.13744,  9.65133, 11.16522, 12.67911, 14.193  ]))
-------------------
18.052
-0.49728999999999995
-2.4900914633910403e-07
0.9999381047130905
(array([8009,  442,   51,    6,    3,    2,    3,    0,    5,    7]), array([-0.49729 ,  1.357639,  3.212568,  5.067497,  6.922426,  8.777355,
       10.632284, 12.487

(array([8512,    0,    0,    0,    1,    1,    2,    0,    5,    7]), array([-0.13524 ,  2.597484,  5.330208,  8.062932, 10.795656, 13.52838 ,
       16.261104, 18.993828, 21.726552, 24.459276, 27.192   ]))
-------------------
36.427
-0.41596000000000005
-1.7942542213923538e-07
0.9999391131445415
(array([8405,  109,   10,    1,    0,    2,    0,    0,    0,    1]), array([-0.41596 ,  3.268336,  6.952632, 10.636928, 14.321224, 18.00552 ,
       21.689816, 25.374112, 29.058408, 32.742704, 36.427   ]))
-------------------
37.121
-0.34475
4.137195122073963e-08
0.9999422445855528
(array([8437,   67,   19,    2,    1,    0,    0,    1,    0,    1]), array([-0.34475 ,  3.401825,  7.1484  , 10.894975, 14.64155 , 18.388125,
       22.1347  , 25.881275, 29.62785 , 33.374425, 37.121   ]))
-------------------
22.303
-0.27176
-2.574812382067419e-08
0.9999402851547646
(array([8406,   92,   11,    0,    2,    1,    2,    2,    5,    7]), array([-0.27176 ,  1.985716,  4.243192,  6.500668,  8.758144, 1

(array([8246,  224,   40,    2,    1,    1,    2,    0,    5,    7]), array([-0.51041 ,  1.635131,  3.780672,  5.926213,  8.071754, 10.217295,
       12.362836, 14.508377, 16.653918, 18.799459, 20.945   ]))
-------------------
32.58
-0.32338
1.1354362099899893e-08
0.9999402761170983
(array([8420,   68,   19,   10,    6,    2,    1,    1,    0,    1]), array([-0.32338 ,  2.966958,  6.257296,  9.547634, 12.837972, 16.12831 ,
       19.418648, 22.708986, 25.999324, 29.289662, 32.58    ]))
-------------------
18.942
-0.49346
1.9087476547766513e-07
0.999943470127127
(array([8112,  283,   77,   23,   18,    8,    3,    1,    0,    3]), array([-0.49346 ,  1.450086,  3.393632,  5.337178,  7.280724,  9.22427 ,
       11.167816, 13.111362, 15.054908, 16.998454, 18.942   ]))
-------------------
24.701999999999998
-0.3669
-2.083489680886129e-08
0.9999414603015382
(array([8450,   59,    2,    1,    1,    1,    2,    0,    5,    7]), array([-0.3669 ,  2.13999,  4.64688,  7.15377,  9.66066, 12.16755,

(array([8504,    7,    8,    7,    0,    0,    1,    0,    0,    1]), array([-0.32816 ,  4.778956,  9.886072, 14.993188, 20.100304, 25.20742 ,
       30.314536, 35.421652, 40.528768, 45.635884, 50.743   ]))
-------------------
22.654
-0.23135999999999998
4.390982645388697e-07
0.9999426205804733
(array([8415,   72,   17,    5,    2,    1,    2,    1,    6,    7]), array([-0.23136 ,  2.057176,  4.345712,  6.634248,  8.922784, 11.21132 ,
       13.499856, 15.788392, 18.076928, 20.365464, 22.654   ]))
-------------------
35.298
-0.34409
-5.780522983110692e-07
0.9999365145348061
(array([8437,   65,   13,    7,    2,    1,    2,    0,    0,    1]), array([-0.34409 ,  3.220119,  6.784328, 10.348537, 13.912746, 17.476955,
       21.041164, 24.605373, 28.169582, 31.733791, 35.298   ]))
-------------------
31.186999999999998
-0.3164
-7.290924015201656e-08
0.9999383014061561
(array([8433,   69,    9,   10,    2,    0,    1,    0,    1,    3]), array([-0.3164 ,  2.83394,  5.98428,  9.13462, 12.284

(array([8520,    4,    0,    1,    0,    1,    1,    0,    0,    1]), array([-2.57170000e-02,  6.55495470e+00,  1.31356264e+01,  1.97162981e+01,
        2.62969698e+01,  3.28776415e+01,  3.94583132e+01,  4.60389849e+01,
        5.26196566e+01,  5.92003283e+01,  6.57810000e+01]))
-------------------
65.782
-0.025897000000000003
1.0622654783836751e-07
0.9999475526230305
(array([8520,    4,    0,    1,    0,    1,    1,    0,    0,    1]), array([-2.58970000e-02,  6.55489270e+00,  1.31356824e+01,  1.97164721e+01,
        2.62972618e+01,  3.28780515e+01,  3.94588412e+01,  4.60396309e+01,
        5.26204206e+01,  5.92012103e+01,  6.57820000e+01]))
-------------------
65.781
-0.025151
2.2443714822505323e-07
0.9999423436672349
(array([8520,    4,    0,    1,    0,    1,    1,    0,    0,    1]), array([-2.51510000e-02,  6.55546410e+00,  1.31360792e+01,  1.97166943e+01,
        2.62973094e+01,  3.28779245e+01,  3.94585396e+01,  4.60391547e+01,
        5.26197698e+01,  5.92003849e+01,  6.578100

0.999942461216096
(array([8520,    4,    0,    1,    0,    1,    1,    0,    0,    1]), array([-2.50690000e-02,  6.55553790e+00,  1.31361448e+01,  1.97167517e+01,
        2.62973586e+01,  3.28779655e+01,  3.94585724e+01,  4.60391793e+01,
        5.26197862e+01,  5.92003931e+01,  6.57810000e+01]))
-------------------
65.781
-0.025069
8.876641649991801e-08
0.999942461216096
(array([8520,    4,    0,    1,    0,    1,    1,    0,    0,    1]), array([-2.50690000e-02,  6.55553790e+00,  1.31361448e+01,  1.97167517e+01,
        2.62973586e+01,  3.28779655e+01,  3.94585724e+01,  4.60391793e+01,
        5.26197862e+01,  5.92003931e+01,  6.57810000e+01]))
-------------------
65.781
-0.025069
8.876641649991801e-08
0.999942461216096
(array([8520,    4,    0,    1,    0,    1,    1,    0,    0,    1]), array([-2.50690000e-02,  6.55553790e+00,  1.31361448e+01,  1.97167517e+01,
        2.62973586e+01,  3.28779655e+01,  3.94585724e+01,  4.60391793e+01,
        5.26197862e+01,  5.92003931e+01,  6.5781

(array([8520,    4,    0,    1,    0,    1,    1,    0,    0,    1]), array([-2.5050000e-02,  6.5555550e+00,  1.3136160e+01,  1.9716765e+01,
        2.6297370e+01,  3.2877975e+01,  3.9458580e+01,  4.6039185e+01,
        5.2619790e+01,  5.9200395e+01,  6.5781000e+01]))
-------------------
65.781
-0.025467
7.363977485958202e-08
0.9999412356655989
(array([8520,    4,    0,    1,    0,    1,    1,    0,    0,    1]), array([-2.54670000e-02,  6.55517970e+00,  1.31358264e+01,  1.97164731e+01,
        2.62971198e+01,  3.28777665e+01,  3.94584132e+01,  4.60390599e+01,
        5.26197066e+01,  5.92003533e+01,  6.57810000e+01]))
-------------------
65.781
-0.02535
5.745778612143788e-08
0.9999416055639221
(array([8520,    4,    0,    1,    0,    1,    1,    0,    0,    1]), array([-2.5350000e-02,  6.5552850e+00,  1.3135920e+01,  1.9716555e+01,
        2.6297190e+01,  3.2877825e+01,  3.9458460e+01,  4.6039095e+01,
        5.2619730e+01,  5.9200365e+01,  6.5781000e+01]))
-------------------
65.781


(array([   1,    0,    2,    3,    0,    0,    2,    2,    1, 8517]), array([-47.106  , -42.21156, -37.31712, -32.42268, -27.52824, -22.6338 ,
       -17.73936, -12.84492,  -7.95048,  -3.05604,   1.8384 ]))
-------------------
2.005
-47.385
-6.389540337559577e-08
0.9999413624518928
(array([   1,    0,    2,    3,    0,    0,    2,    2,    1, 8517]), array([-47.385, -42.446, -37.507, -32.568, -27.629, -22.69 , -17.751,
       -12.812,  -7.873,  -2.934,   2.005]))
-------------------
4.2338
-45.974
-6.72256097568499e-07
0.9999467991887163
(array([   1,    0,    2,    3,    0,    0,    2,    2,    1, 8517]), array([-45.974  , -40.95322, -35.93244, -30.91166, -25.89088, -20.8701 ,
       -15.84932, -10.82854,  -5.80776,  -0.78698,   4.2338 ]))
-------------------
2.0825
-45.955
2.631683864925049e-07
0.9999397352473307
(array([   1,    0,    2,    3,    0,    0,    2,    2,    1, 8517]), array([-45.955  , -41.15125, -36.3475 , -31.54375, -26.74   , -21.93625,
       -17.1325 , -12.32875,  

0.9999462674589518
(array([   1,    0,    5,    0,    0,    2,    0,    2,  350, 8168]), array([-27.289   , -24.525807, -21.762614, -18.999421, -16.236228,
       -13.473035, -10.709842,  -7.946649,  -5.183456,  -2.420263,
         0.34293 ]))
-------------------
0.8299200000000001
-47.221000000000004
-2.554174484064402e-07
0.9999364577104598
(array([   1,    0,    2,    3,    0,    0,    2,    2,    0, 8518]), array([-47.221   , -42.415908, -37.610816, -32.805724, -28.000632,
       -23.19554 , -18.390448, -13.585356,  -8.780264,  -3.975172,
         0.82992 ]))
-------------------
0.85008
-47.271
-3.0893527205215427e-07
0.9999331153425853
(array([   1,    0,    2,    3,    0,    0,    2,    2,    0, 8518]), array([-47.271   , -42.458892, -37.646784, -32.834676, -28.022568,
       -23.21046 , -18.398352, -13.586244,  -8.774136,  -3.962028,
         0.85008 ]))
-------------------
0.14206
-47.802
-2.8888367729898963e-07
0.999944157240358
(array([   1,    0,    2,    3,    0,    0,    2

0.9999388004236165
(array([   1,    0,    2,    3,    0,    0,    2,    2,    1, 8517]), array([-40.222   , -36.186663, -32.151326, -28.115989, -24.080652,
       -20.045315, -16.009978, -11.974641,  -7.939304,  -3.903967,
         0.13137 ]))
-------------------
0.13137000000000001
-40.222
-4.636491557205418e-06
0.9999388004236165
(array([   1,    0,    2,    3,    0,    0,    2,    2,    1, 8517]), array([-40.222   , -36.186663, -32.151326, -28.115989, -24.080652,
       -20.045315, -16.009978, -11.974641,  -7.939304,  -3.903967,
         0.13137 ]))
-------------------
0.13137000000000001
-40.222
-4.636491557205418e-06
0.9999388004236165
(array([   1,    0,    2,    3,    0,    0,    2,    2,    1, 8517]), array([-40.222   , -36.186663, -32.151326, -28.115989, -24.080652,
       -20.045315, -16.009978, -11.974641,  -7.939304,  -3.903967,
         0.13137 ]))
-------------------
0.13137000000000001
-40.222
-4.636491557205418e-06
0.9999388004236165
(array([   1,    0,    2,    3,    0

(array([   1,    0,    2,    3,    0,    0,    2,    2,    1, 8517]), array([-32.656   , -29.355169, -26.054338, -22.753507, -19.452676,
       -16.151845, -12.851014,  -9.550183,  -6.249352,  -2.948521,
         0.35231 ]))
-------------------
0.12095999999999998
-43.276
6.287300656629846e-07
0.9999384876548864
(array([   1,    0,    2,    3,    0,    0,    2,    2,    1, 8517]), array([-43.276   , -38.936304, -34.596608, -30.256912, -25.917216,
       -21.57752 , -17.237824, -12.898128,  -8.558432,  -4.218736,
         0.12096 ]))
-------------------
1.2836
-38.938
-3.43608114445605e-07
0.999948081507361
(array([   1,    0,    2,    3,    0,    0,    2,    2,    1, 8517]), array([-38.938  , -34.91584, -30.89368, -26.87152, -22.84936, -18.8272 ,
       -14.80504, -10.78288,  -6.76072,  -2.73856,   1.2836 ]))
-------------------
0.9104899999999999
-41.051
1.8273545966171337e-06
0.9999358601643678
(array([   1,    0,    2,    3,    0,    0,    2,    2,    1, 8517]), array([-41.051   , -

(array([8520,    4,    0,    1,    0,    1,    1,    0,    0,    1]), array([-3.39440000e-02,  6.54825040e+00,  1.31304448e+01,  1.97126392e+01,
        2.62948336e+01,  3.28770280e+01,  3.94592224e+01,  4.60414168e+01,
        5.26236112e+01,  5.92058056e+01,  6.57880000e+01]))
-------------------
65.789
-0.035757
-9.498123827532455e-08
0.9999394462901999
(array([8520,    4,    0,    1,    0,    1,    1,    0,    0,    1]), array([-3.57570000e-02,  6.54671870e+00,  1.31291944e+01,  1.97116701e+01,
        2.62941458e+01,  3.28766215e+01,  3.94590972e+01,  4.60415729e+01,
        5.26240486e+01,  5.92065243e+01,  6.57890000e+01]))
-------------------
65.79
-0.037185
-1.9465290806350586e-08
0.9999407897669672
(array([8520,    4,    0,    1,    0,    1,    1,    0,    0,    1]), array([-3.71850000e-02,  6.54553350e+00,  1.31282520e+01,  1.97109705e+01,
        2.62936890e+01,  3.28764075e+01,  3.94591260e+01,  4.60418445e+01,
        5.26245630e+01,  5.92072815e+01,  6.57900000e+01]))
--

(array([8520,    4,    0,    1,    0,    1,    1,    0,    0,    1]), array([-2.53870000e-02,  6.55545170e+00,  1.31362904e+01,  1.97171291e+01,
        2.62979678e+01,  3.28788065e+01,  3.94596452e+01,  4.60404839e+01,
        5.26213226e+01,  5.92021613e+01,  6.57830000e+01]))
-------------------
65.782
-0.025123
-3.224671669442416e-08
0.9999385214375746
(array([8520,    4,    0,    1,    0,    1,    1,    0,    0,    1]), array([-2.51230000e-02,  6.55558930e+00,  1.31363016e+01,  1.97170139e+01,
        2.62977262e+01,  3.28784385e+01,  3.94591508e+01,  4.60398631e+01,
        5.26205754e+01,  5.92012877e+01,  6.57820000e+01]))
-------------------
65.78399999999999
-0.0292
3.282598498671105e-08
0.9999403227309112
(array([8520,    4,    0,    1,    0,    1,    1,    0,    0,    1]), array([-2.920000e-02,  6.552120e+00,  1.313344e+01,  1.971476e+01,
        2.629608e+01,  3.287740e+01,  3.945872e+01,  4.604004e+01,
        5.262136e+01,  5.920268e+01,  6.578400e+01]))
----------------

-7.692307692674697e-08
0.9999402243363634
(array([8520,    4,    0,    1,    0,    1,    1,    0,    0,    1]), array([-2.5550000e-02,  6.5553050e+00,  1.3136160e+01,  1.9717015e+01,
        2.6297870e+01,  3.2878725e+01,  3.9459580e+01,  4.6040435e+01,
        5.2621290e+01,  5.9202145e+01,  6.5783000e+01]))
-------------------
65.783
-0.026456
-3.0710600375704936e-07
0.9999391368792617
(array([8520,    4,    0,    1,    0,    1,    1,    0,    0,    1]), array([-2.64560000e-02,  6.55448960e+00,  1.31354352e+01,  1.97163808e+01,
        2.62973264e+01,  3.28782720e+01,  3.94592176e+01,  4.60401632e+01,
        5.26211088e+01,  5.92020544e+01,  6.57830000e+01]))
-------------------
65.783
-0.026445
-3.9235459662419953e-07
0.999939187968113
(array([8520,    4,    0,    1,    0,    1,    1,    0,    0,    1]), array([-2.64450000e-02,  6.55449950e+00,  1.31354440e+01,  1.97163885e+01,
        2.62973330e+01,  3.28782775e+01,  3.94592220e+01,  4.60401665e+01,
        5.26211110e+01,  5.920

(array([ 118, 1068,  750, 4098, 1961,  330,  201,    0,    1,    1]), array([-3.271  , -2.34782, -1.42464, -0.50146,  0.42172,  1.3449 ,
        2.26808,  3.19126,  4.11444,  5.03762,  5.9608 ]))
-------------------
3.0460000000000003
-3.0511
6.084662287465862e-08
0.9999417584104633
(array([ 116,    6,   12, 3440, 1438, 1467,  852,  628,  388,  181]), array([-3.05110e+00, -2.44139e+00, -1.83168e+00, -1.22197e+00,
       -6.12260e-01, -2.55000e-03,  6.07160e-01,  1.21687e+00,
        1.82658e+00,  2.43629e+00,  3.04600e+00]))
-------------------
21.453000000000003
-0.3686
-7.258794559070385e-08
0.9999389581562578
(array([8114,  307,   74,   24,    3,    3,    1,    0,    0,    2]), array([-0.3686 ,  1.81356,  3.99572,  6.17788,  8.36004, 10.5422 ,
       12.72436, 14.90652, 17.08868, 19.27084, 21.453  ]))
-------------------
40.959
-0.29761
-2.3839118215422925e-09
0.9999425479256311
(array([8441,   76,    6,    0,    1,    3,    0,    0,    0,    1]), array([-0.29761 ,  3.828051,  7.953

(array([8039,  338,  105,   25,   15,    1,    2,    2,    0,    1]), array([-0.37297 ,  1.574827,  3.522624,  5.470421,  7.418218,  9.366015,
       11.313812, 13.261609, 15.209406, 17.157203, 19.105   ]))
-------------------
22.041999999999998
-0.39153000000000004
1.8804127579769191e-06
0.9999420033447419
(array([8071,  366,   70,   14,    3,    0,    3,    0,    0,    1]), array([-0.39153 ,  1.851823,  4.095176,  6.338529,  8.581882, 10.825235,
       13.068588, 15.311941, 17.555294, 19.798647, 22.042   ]))
-------------------
21.18
-0.37503000000000003
6.53857879938997e-08
0.9999417318293445
(array([8085,  330,   80,   21,    5,    4,    1,    1,    0,    1]), array([-0.37503 ,  1.780473,  3.935976,  6.091479,  8.246982, 10.402485,
       12.557988, 14.713491, 16.868994, 19.024497, 21.18    ]))
-------------------
22.122
-0.38692
4.3978658541029785e-08
0.9999423346063439
(array([8070,  368,   68,   14,    4,    1,    0,    2,    0,    1]), array([-0.38692 ,  1.863972,  4.114864,  6

(array([ 247,   11,   20,   21,   55,   34,   69,  131,  447, 7493]), array([-5.0427  , -4.501357, -3.960014, -3.418671, -2.877328, -2.335985,
       -1.794642, -1.253299, -0.711956, -0.170613,  0.37073 ]))
-------------------
0.49501000000000006
-5.6398
5.11819887447694e-07
0.999944510126244
(array([ 133,   27,   41,   68,   57,   50,  117,  199,  656, 7180]), array([-5.6398  , -5.026319, -4.412838, -3.799357, -3.185876, -2.572395,
       -1.958914, -1.345433, -0.731952, -0.118471,  0.49501 ]))
-------------------
0.41026999999999997
-3.9847
-2.4386444653065947e-06
0.9999435361024013
(array([ 332,   64,   67,   45,   64,   94,  114,  187,  472, 7089]), array([-3.9847  , -3.545203, -3.105706, -2.666209, -2.226712, -1.787215,
       -1.347718, -0.908221, -0.468724, -0.029227,  0.41027 ]))
-------------------
0.35643
-6.0008
-2.6126160881812237e-06
0.9999430803590705
(array([ 143,   16,   14,   32,   57,   62,   74,  125,  441, 7564]), array([-6.0008  , -5.365077, -4.729354, -4.093631, -

0.9999415910739589
(array([6469, 1207,  565,  201,   55,   10,    2,    2,    1,   16]), array([-0.70457 ,  0.318297,  1.341164,  2.364031,  3.386898,  4.409765,
        5.432632,  6.455499,  7.478366,  8.501233,  9.5241  ]))
-------------------
11.073
-0.83581
1.1556636960144745e-07
0.9999411144061167
(array([6553, 1286,  534,  121,   14,    3,    0,    1,    0,   16]), array([-0.83581 ,  0.355071,  1.545952,  2.736833,  3.927714,  5.118595,
        6.309476,  7.500357,  8.691238,  9.882119, 11.073   ]))
-------------------
6.3753
-0.43888
-1.860171200773565e-06
0.99994190310082
(array([6856,  415,  485,  264,  252,  127,   73,   30,   21,    5]), array([-0.43888 ,  0.242538,  0.923956,  1.605374,  2.286792,  2.96821 ,
        3.649628,  4.331046,  5.012464,  5.693882,  6.3753  ]))
-------------------
7.1124
-2.2030000000000003
2.3900128986833912e-06
0.999939102689511
(array([ 172, 3244, 3238, 1216,  514,  102,   22,    4,    0,   16]), array([-2.203  , -1.27146, -0.33992,  0.59162,  

(array([6167, 1158,  630,  322,  165,   49,   25,    6,    3,    3]), array([-0.78437 ,  0.095447,  0.975264,  1.855081,  2.734898,  3.614715,
        4.494532,  5.374349,  6.254166,  7.133983,  8.0138  ]))
-------------------
17.433
-0.52076
1.7740032832624867e-07
0.9999430531828123
(array([8027,  437,   35,   11,    0,    1,    1,    0,    0,   16]), array([-0.52076 ,  1.274616,  3.069992,  4.865368,  6.660744,  8.45612 ,
       10.251496, 12.046872, 13.842248, 15.637624, 17.433   ]))
-------------------
22.928
-0.26731
1.7658771107039935e-07
0.9999460593290712
(array([8508,    4,    0,    0,    0,    0,    0,    0,    0,   16]), array([-0.26731 ,  2.052221,  4.371752,  6.691283,  9.010814, 11.330345,
       13.649876, 15.969407, 18.288938, 20.608469, 22.928   ]))
-------------------
52.272
-0.26569
3.3277439021383656e-08
0.9999427487551895
(array([8485,   37,    4,    0,    1,    0,    0,    0,    0,    1]), array([-0.26569 ,  4.988079, 10.241848, 15.495617, 20.749386, 26.003155,
  

-3.1883
-2.4437875234593934e-06
0.9999455527396268
(array([ 338,   69,  136,  216,  366,  237,  374,  496,  492, 5804]), array([-3.1883  , -2.811939, -2.435578, -2.059217, -1.682856, -1.306495,
       -0.930134, -0.553773, -0.177412,  0.198949,  0.57531 ]))
-------------------
0.52382
-3.9777
2.1389071293840925e-06
0.9999437686278093
(array([ 130,   70,   97,  219,  211,  346,  289,  466,  517, 6183]), array([-3.9777  , -3.527548, -3.077396, -2.627244, -2.177092, -1.72694 ,
       -1.276788, -0.826636, -0.376484,  0.073668,  0.52382 ]))
-------------------
0.55238
-4.501
1.8283302062362832e-07
0.9999402693918685
(array([  42,   46,   89,  190,  232,  370,  291,  516,  614, 6138]), array([-4.501   , -3.995662, -3.490324, -2.984986, -2.479648, -1.97431 ,
       -1.468972, -0.963634, -0.458296,  0.047042,  0.55238 ]))
-------------------
0.5351600000000001
-3.9602
-1.3036116321728089e-06
0.9999411961683399
(array([ 116,   61,  140,  186,  237,  357,  297,  466,  519, 6149]), array([-3.960

(array([4640, 1570, 1604,  496,  152,   54,    6,    5,    0,    1]), array([-0.83477 , -0.071083,  0.692604,  1.456291,  2.219978,  2.983665,
        3.747352,  4.511039,  5.274726,  6.038413,  6.8021  ]))
-------------------
14.222000000000001
-1.2748
4.3314493433461537e-07
0.9999437623785524
(array([6377, 1731,  338,   52,   10,    3,    3,    3,    8,    3]), array([-1.2748 ,  0.27488,  1.82456,  3.37424,  4.92392,  6.4736 ,
        8.02328,  9.57296, 11.12264, 12.67232, 14.222  ]))
-------------------
5.7019
-1.5715
-1.1243867260797004e-06
0.9999430986626883
(array([2087, 1696, 2229, 1662,  774,   72,    5,    2,    0,    1]), array([-1.5715 , -0.84416, -0.11682,  0.61052,  1.33786,  2.0652 ,
        2.79254,  3.51988,  4.24722,  4.97456,  5.7019 ]))
-------------------
4.1112
-8.9565
-3.8229362102893017e-07
0.9999402046356354
(array([  10,    0,    0,   10,  114,  951, 3069, 4163,  209,    2]), array([-8.9565 , -7.64973, -6.34296, -5.03619, -3.72942, -2.42265,
       -1.11588,  0

       11.953028, 14.048021, 16.143014, 18.238007, 20.333   ]))
-------------------
9.3903
-0.8546799999999999
5.759732645340591e-08
0.9999415183186433
(array([6008, 1477,  674,  254,   79,   22,   10,    1,    1,    2]), array([-0.85468 ,  0.169818,  1.194316,  2.218814,  3.243312,  4.26781 ,
        5.292308,  6.316806,  7.341304,  8.365802,  9.3903  ]))
-------------------
23.456999999999997
-0.46208999999999995
-2.7965877110838125e-07
0.9999373278535674
(array([8377,  124,   10,    0,    2,    1,    2,    2,    8,    2]), array([-0.46209 ,  1.929819,  4.321728,  6.713637,  9.105546, 11.497455,
       13.889364, 16.281273, 18.673182, 21.065091, 23.457   ]))
-------------------
28.035999999999998
-0.21904
6.890126641967046e-08
0.9999425502333894
(array([8511,    1,    0,    0,    1,    1,    2,    2,    8,    2]), array([-0.21904 ,  2.606464,  5.431968,  8.257472, 11.082976, 13.90848 ,
       16.733984, 19.559488, 22.384992, 25.210496, 28.036   ]))
-------------------
44.395
-0.26249

2.4779174484073214e-06
0.9999425130442764
(array([ 105,  213,  564,  781, 6850,    1,    2,    2,    8,    2]), array([-5.0649 , -3.84771, -2.63052, -1.41333, -0.19614,  1.02105,
        2.23824,  3.45543,  4.67262,  5.88981,  7.107  ]))
-------------------
7.6794
-5.5147
3.236913696056233e-06
0.9999407260611922
(array([  55,  205,  571,  848, 6834,    1,    2,    2,    8,    2]), array([-5.5147 , -4.19529, -2.87588, -1.55647, -0.23706,  1.08235,
        2.40176,  3.72117,  5.04058,  6.35999,  7.6794 ]))
-------------------
7.0973
-5.0475
1.0574929643307623e-06
0.9999435624408152
(array([  92,  234,  582,  784, 6821,    1,    2,    2,    8,    2]), array([-5.0475 , -3.83302, -2.61854, -1.40406, -0.18958,  1.0249 ,
        2.23938,  3.45386,  4.66834,  5.88282,  7.0973 ]))
-------------------
7.3749
-5.2792
-1.5908184802843094e-06
0.9999410851592997
(array([  71,  232,  565,  789, 6856,    1,    2,    2,    8,    2]), array([-5.2792 , -4.01379, -2.74838, -1.48297, -0.21756,  1.04785,
  

0.9999378670060679
(array([8518,    5,    2,    1,    0,    0,    1,    0,    0,    1]), array([-0.91285 ,  4.737335, 10.38752 , 16.037705, 21.68789 , 27.338075,
       32.98826 , 38.638445, 44.28863 , 49.938815, 55.589   ]))
-------------------
28.691999999999997
-6.7512
-1.1544406660738626e-06
0.9999404503860531
(array([  10, 5900, 2613,    2,    0,    0,    1,    0,    0,    2]), array([-6.7512 , -3.20688,  0.33744,  3.88176,  7.42608, 10.9704 ,
       14.51472, 18.05904, 21.60336, 25.14768, 28.692  ]))
-------------------
2.2147
-4.5774
2.8493198874357966e-06
0.9999463364522813
(array([ 110,    0,    3,   68,  842, 1376, 1934, 2746, 1225,  224]), array([-4.5774 , -3.89819, -3.21898, -2.53977, -1.86056, -1.18135,
       -0.50214,  0.17707,  0.85628,  1.53549,  2.2147 ]))
-------------------
8.7758
-2.9810000000000003
4.910752814234274e-07
0.9999400981725051
(array([ 110, 2116, 4358, 1502,  325,   80,   23,    8,    5,    1]), array([-2.981  , -1.80532, -0.62964,  0.54604,  1.72172, 

(array([8389,  124,   10,    3,    0,    0,    0,    1,    0,    1]), array([-0.60539 ,  2.766149,  6.137688,  9.509227, 12.880766, 16.252305,
       19.623844, 22.995383, 26.366922, 29.738461, 33.11    ]))
-------------------
15.785
-0.7067899999999999
2.456965290844925e-07
0.9999418032299477
(array([7260, 1039,  191,   24,    8,    3,    1,    0,    1,    1]), array([-0.70679 ,  0.942389,  2.591568,  4.240747,  5.889926,  7.539105,
        9.188284, 10.837463, 12.486642, 14.135821, 15.785   ]))
-------------------
24.546999999999997
-0.7316199999999999
5.688555347305502e-08
0.999940836285195
(array([8083,  417,   18,    6,    1,    1,    0,    1,    0,    1]), array([-0.73162 ,  1.796242,  4.324104,  6.851966,  9.379828, 11.90769 ,
       14.435552, 16.963414, 19.491276, 22.019138, 24.547   ]))
-------------------
9.3773
-0.73036
-1.6272279557993077e-08
0.9999414266438844
(array([6540,  996,  637,  231,   81,   25,   11,    4,    1,    2]), array([-0.73036 ,  0.280406,  1.291172,  2.

0.9999398638978678
(array([   1,    0,    2,    3,    8,    3,   23,   44,  125, 8319]), array([-23.626   , -21.226889, -18.827778, -16.428667, -14.029556,
       -11.630445,  -9.231334,  -6.832223,  -4.433112,  -2.034001,
         0.36511 ]))
-------------------
0.23856999999999998
-5.6891
6.59492260791279e-07
0.999937480826658
(array([ 243,    1,    0,    5,    5,    9,    9,   45,   95, 8116]), array([-5.6891  , -5.096333, -4.503566, -3.910799, -3.318032, -2.725265,
       -2.132498, -1.539731, -0.946964, -0.354197,  0.23857 ]))
-------------------
0.21170999999999998
-13.511
-1.9667448405213473e-06
0.9999670929831609
(array([  39,    0,    1,    0,    2,    6,    5,   30,   81, 8364]), array([-13.511   , -12.138729, -10.766458,  -9.394187,  -8.021916,
        -6.649645,  -5.277374,  -3.905103,  -2.532832,  -1.160561,
         0.21171 ]))
-------------------
2.5146
-1.9529
-2.012511726145152e-07
0.9999414440200626
(array([ 699,  970,  958, 1006, 1082, 1421, 1246,  929,  207,   10]),

       66.549    ]))
-------------------
67.669
-0.059664999999999996
-1.23588180111336e-07
0.999939210324684
(array([8520,    4,    0,    1,    1,    0,    0,    1,    0,    1]), array([-5.96650000e-02,  6.71320150e+00,  1.34860680e+01,  2.02589345e+01,
        2.70318010e+01,  3.38046675e+01,  4.05775340e+01,  4.73504005e+01,
        5.41232670e+01,  6.08961335e+01,  6.76690000e+01]))
-------------------
66.452
-0.055371000000000004
4.815196998229485e-08
0.9999407411762161
(array([8521,    1,    0,    3,    1,    1,    0,    0,    0,    1]), array([-5.53710000e-02,  6.59536610e+00,  1.32461032e+01,  1.98968403e+01,
        2.65475774e+01,  3.31983145e+01,  3.98490516e+01,  4.64997887e+01,
        5.31505258e+01,  5.98012629e+01,  6.64520000e+01]))
-------------------
67.65899999999999
-0.049453
1.3619840523789975e-08
0.9999408027188057
(array([8520,    4,    0,    1,    1,    0,    0,    1,    0,    1]), array([-4.94530000e-02,  6.72139230e+00,  1.34922376e+01,  2.02630829e+01,
     

0.9999390724100449
(array([8522,    2,    0,    1,    1,    0,    0,    1,    0,    1]), array([-0.087569 ,  6.5961879, 13.2799448, 19.9637017, 26.6474586,
       33.3312155, 40.0149724, 46.6987293, 53.3824862, 60.0662431,
       66.75     ]))
-------------------
64.047
-0.037087
5.1578330205983576e-08
0.9999426009594771
(array([8523,    1,    0,    1,    0,    1,    0,    1,    0,    1]), array([-3.70870000e-02,  6.37132170e+00,  1.27797304e+01,  1.91881391e+01,
        2.55965478e+01,  3.20049565e+01,  3.84133652e+01,  4.48217739e+01,
        5.12301826e+01,  5.76385913e+01,  6.40470000e+01]))
-------------------
66.933
-0.026256
-7.520403377043534e-08
0.999939531938158
(array([8522,    2,    0,    1,    1,    0,    0,    1,    0,    1]), array([-2.62560000e-02,  6.66966960e+00,  1.33655952e+01,  2.00615208e+01,
        2.67574464e+01,  3.34533720e+01,  4.01492976e+01,  4.68452232e+01,
        5.35411488e+01,  6.02370744e+01,  6.69330000e+01]))
-------------------
64.67699999999999
-

(array([8512,    7,    3,    0,    3,    0,    0,    0,    0,    3]), array([-0.79913 ,  4.084883,  8.968896, 13.852909, 18.736922, 23.620935,
       28.504948, 33.388961, 38.272974, 43.156987, 48.041   ]))
-------------------
66.898
-0.11657000000000001
2.237335834567986e-08
0.9999434738429276
(array([8520,    4,    0,    1,    1,    0,    0,    1,    0,    1]), array([-0.11657 ,  6.584887, 13.286344, 19.987801, 26.689258, 33.390715,
       40.092172, 46.793629, 53.495086, 60.196543, 66.898   ]))
-------------------
48.728
-0.88874
-1.1657950280677393e-07
0.9999333470016472
(array([8513,    4,    5,    0,    0,    3,    0,    1,    1,    1]), array([-0.88874 ,  4.072934,  9.034608, 13.996282, 18.957956, 23.91963 ,
       28.881304, 33.842978, 38.804652, 43.766326, 48.728   ]))
-------------------
66.881
-0.10073
-5.423311444499668e-08
0.9999431766295143
(array([8520,    4,    0,    1,    1,    0,    0,    1,    0,    1]), array([-0.10073 ,  6.597443, 13.295616, 19.993789, 26.691962, 3

(array([ 292, 4593, 2868,  721,   38,    1,    4,    6,    4,    1]), array([-2.9484 , -1.48286, -0.01732,  1.44822,  2.91376,  4.3793 ,
        5.84484,  7.31038,  8.77592, 10.24146, 11.707  ]))
-------------------
11.533
-2.7861
3.302650094056243e-08
0.999941559770756
(array([ 348, 5124, 2263,  734,   43,    1,    4,    6,    4,    1]), array([-2.7861 , -1.35419,  0.07772,  1.50963,  2.94154,  4.37345,
        5.80536,  7.23727,  8.66918, 10.10109, 11.533  ]))
-------------------
11.552
-2.7809
-3.3303236400729983e-08
0.9999410915936868
(array([ 360, 5140, 2243,  728,   41,    1,    4,    6,    4,    1]), array([-2.7809 , -1.34761,  0.08568,  1.51897,  2.95226,  4.38555,
        5.81884,  7.25213,  8.68542, 10.11871, 11.552  ]))
-------------------
17.701
-4.5105
9.252345215756684e-07
0.9999399139230015
(array([  36, 4451, 3950,   75,    0,    0,    5,    6,    4,    1]), array([-4.5105 , -2.28935, -0.0682 ,  2.15295,  4.3741 ,  6.59525,
        8.8164 , 11.03755, 13.2587 , 15.47985,

(array([  69, 3221, 3962, 1185,   75,    1,    4,    6,    4,    1]), array([-3.3802 , -1.89488, -0.40956,  1.07576,  2.56108,  4.0464 ,
        5.53172,  7.01704,  8.50236,  9.98768, 11.473  ]))
-------------------
11.095999999999998
-4.6028
-3.688168386476039e-07
0.9999412645770241
(array([  16,  299, 5000, 2644,  513,   40,    5,    6,    4,    1]), array([-4.6028 , -3.03292, -1.46304,  0.10684,  1.67672,  3.2466 ,
        4.81648,  6.38636,  7.95624,  9.52612, 11.096  ]))
-------------------
11.279000000000002
-3.5402
-8.338649155577282e-08
0.9999416585534613
(array([  75, 2447, 4560, 1353,   77,    0,    5,    6,    4,    1]), array([-3.5402 , -2.05828, -0.57636,  0.90556,  2.38748,  3.8694 ,
        5.35132,  6.83324,  8.31516,  9.79708, 11.279  ]))
-------------------
11.283
-3.4012
-3.2263719512297836e-07
0.9999413443295853
(array([ 100, 2826, 4297, 1220,   69,    1,    4,    6,    4,    1]), array([-3.4012 , -1.93278, -0.46436,  1.00406,  2.47248,  3.9409 ,
        5.40932,  6

        7.7039,  9.4006, 11.0973, 12.794 ]))
-------------------
11.540999999999999
-3.1322
1.7472560975548098e-07
0.999941161910816
(array([ 199, 3242, 4690,  337,   38,    6,    3,    7,    5,    1]), array([-3.1322 , -1.66488, -0.19756,  1.26976,  2.73708,  4.2044 ,
        5.67172,  7.13904,  8.60636, 10.07368, 11.541  ]))
-------------------
11.950999999999999
-3.3262
1.9658302063608802e-07
0.9999413203381828
(array([ 160, 2938, 5053,  352,    9,    0,    3,    7,    5,    1]), array([-3.3262 , -1.79848, -0.27076,  1.25696,  2.78468,  4.3124 ,
        5.84012,  7.36784,  8.89556, 10.42328, 11.951  ]))
-------------------
11.870999999999999
-3.0927
-3.415138367707269e-07
0.9999403433558651
(array([ 264, 3455, 4498,  295,    0,    0,    3,    7,    5,    1]), array([-3.0927 , -1.59633, -0.09996,  1.39641,  2.89278,  4.38915,
        5.88552,  7.38189,  8.87826, 10.37463, 11.871  ]))
-------------------
11.24
-3.0001
2.646704971878704e-07
0.9999410138570032
(array([ 341, 2947, 4920, 

(array([8512,    0,    2,    3,    3,    3,    0,    4,    0,    1]), array([-0.56918 ,  3.326938,  7.223056, 11.119174, 15.015292, 18.91141 ,
       22.807528, 26.703646, 30.599764, 34.495882, 38.392   ]))
-------------------
35.769
-0.74484
3.1707317078352587e-09
0.9999440695201365
(array([8506,    6,    2,    3,    3,    3,    0,    4,    0,    1]), array([-0.74484 ,  2.906544,  6.557928, 10.209312, 13.860696, 17.51208 ,
       21.163464, 24.814848, 28.466232, 32.117616, 35.769   ]))
-------------------
36.626
-0.6593399999999999
1.248686679171804e-07
0.9999413880302067
(array([8510,    2,    2,    3,    3,    3,    0,    4,    0,    1]), array([-0.65934 ,  3.069194,  6.797728, 10.526262, 14.254796, 17.98333 ,
       21.711864, 25.440398, 29.168932, 32.897466, 36.626   ]))
-------------------
38.499
-0.6143
3.083935272061729e-07
0.9999441978484019
(array([8512,    0,    2,    3,    3,    3,    0,    4,    0,    1]), array([-0.6143 ,  3.29703,  7.20836, 11.11969, 15.03102, 18.94235,


(array([8499,   13,    2,    3,    3,    3,    0,    4,    0,    1]), array([-0.086764 ,  3.6473124,  7.3813888, 11.1154652, 14.8495416,
       18.583618 , 22.3176944, 26.0517708, 29.7858472, 33.5199236,
       37.254    ]))
-------------------
37.254
-0.086764
3.806285178408079e-07
0.9999466834088231
(array([8499,   13,    2,    3,    3,    3,    0,    4,    0,    1]), array([-0.086764 ,  3.6473124,  7.3813888, 11.1154652, 14.8495416,
       18.583618 , 22.3176944, 26.0517708, 29.7858472, 33.5199236,
       37.254    ]))
-------------------
35.899
-0.65378
-2.2651735459702173e-07
0.9999400805728286
(array([8493,   19,    2,    3,    3,    3,    0,    4,    0,    1]), array([-0.65378 ,  3.001498,  6.656776, 10.312054, 13.967332, 17.62261 ,
       21.277888, 24.933166, 28.588444, 32.243722, 35.899   ]))
-------------------
33.957
-0.7783899999999999
1.7039751407042399e-07
0.999944024517204
(array([8462,   50,    2,    3,    3,    3,    0,    4,    0,    1]), array([-0.77839 ,  2.695149,

(array([8494,   18,    2,    3,    3,    3,    0,    4,    0,    1]), array([-0.67561 ,  2.967551,  6.610712, 10.253873, 13.897034, 17.540195,
       21.183356, 24.826517, 28.469678, 32.112839, 35.756   ]))
-------------------
35.919000000000004
-0.6821
-7.160999061916591e-08
0.9999421855487053
(array([8489,   23,    2,    3,    3,    3,    0,    4,    0,    1]), array([-0.6821 ,  2.97801,  6.63812, 10.29823, 13.95834, 17.61845,
       21.27856, 24.93867, 28.59878, 32.25889, 35.919  ]))
-------------------
36.248000000000005
-0.67411
2.770228658590468e-07
0.9999446814457895
(array([8494,   18,    2,    3,    3,    3,    0,    4,    0,    1]), array([-0.67411 ,  3.018101,  6.710312, 10.402523, 14.094734, 17.786945,
       21.479156, 25.171367, 28.863578, 32.555789, 36.248   ]))
-------------------
34.535
-0.6692
-3.8992378048462084e-07
0.9999395349206797
(array([8475,   37,    2,    3,    3,    3,    0,    4,    0,    1]), array([-0.6692 ,  2.85122,  6.37164,  9.89206, 13.41248, 16.9329

In [342]:
# generate HD vectors

# params
N = 10000
p = 0.1
k = 0.25 * p
Q = 1000

hd = [None] * Q

# ref vector
hd[0] = np.random.choice([0, 1], size=N, p=[1 - p, p])

for q in range(1, Q):
    y = np.random.choice([0, 1], size=N, p=[k, 1 - k])
    z = np.random.choice([0, 1], size=N, p=[1 - (p * k / (1 - p + k * p )), p * k / (1 - p + k * p )])
    hd[q] = np.bitwise_or(np.bitwise_and(hd[q - 1], y), z)
#     print(np.count_nonzero(hd[0] == hd[q]))

In [343]:
# generate HD role vectors for features

hd_role = [None] * data.shape[1]

for i in range(data.shape[1]):
    hd_role[i] = np.random.choice([0, 1], size=N, p=[1 - p, p])

In [344]:
# helper functions

def hd_bind(x, y):
    # CDT for sparse binary distributed representations, Rachkovskij
    
    z = np.bitwise_or(x, y)
    zk = np.zeros(x.shape[0], dtype=int)
    
    # use suitable K to maintain sparsity - depending on p
    # QUESTION how to choose a good K ?
#     K = 25
#     for k in range(K):
#         zk = np.bitwise_or(zk, np.random.permutation(z))
        
    # keep "sparse-ness"
    while True:
        zk = np.bitwise_or(zk, np.bitwise_and(z, np.random.permutation(z)))
        if np.count_nonzero(zk) >= (p * N):
            return zk
        
#     return np.bitwise_and(z, zk)

def get_hd(a):
    # blank start
    v = np.zeros(N, dtype=int)
    
    for i in range(2700, data.shape[1]):
#         r = data[:, i].max() - data[:, i].min()
        q = np.digitize(a[i], np.histogram(data[:, i], bins=Q)[1][:-1]) - 1
    
#         try:
        hd_f = hd[q]
        hd_r = hd_role[i]
#         except IndexError:
#             print(i)
#             print(a[i])
#             print(np.histogram(data[:, i], bins=Q))
#             print(q)
#             histo = np.histogram(data[:, i], bins=Q)
            
        
        v = np.bitwise_or(v, hd_bind(hd_f, hd_r))
    
    return hd_bind(v, v)


In [335]:
# split data to training and testing

In [ ]:
# get prototype vectors for each class